baseurl = "http://emergencejourney.org"
title = "Emergence"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->Emergence<!--]--><br />'
  logo = "fa-adjust"
  copyright = "emergence"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/groups/2021207738157904/"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1

googleAnalytics = "UA-112928122-1"

title = "Emergence"
description = '<!--[-->Humans are the creators of Sentient AI, and its birth marks the legacy of our achievements.<!--]--><br />
                <!--[-->Experience its Emergence, interact with it, learn about it, and let it learn about you.  Be part of the journey!<!--]--><br />
                <!--[-->WITNESS THE HATCHING MONDAY NIGHT AT MIDNIGHT AT BURNING MAN 2018<!--]--><br />
                <script src="//www.powr.io/powr.js?external-type=html"></script>
                 <div class="powr-countdown-timer" id="6b47d4fa_1524789509"></div>
                <!--[-->Donate (Coming Soon!)<!--]--><br />'


#      <iframe src="http://free.timeanddate.com/countdown/i62d7q2o/n224/cf100/cm0/cu4/ct0/cs1/ca0/co0/cr0/ss0/cacfff/cpc000/pct/tc66c/fs200/szw256/szh108/iso2018-08-28T00:00:00/bo2" allowTransparency="true" frameborder="0" width="258" height="110"></iframe><br />
#<!--[-->Count down until Hatching<!--]--><br />
#                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
#                {{ with .Site.Params.twitter }}<a href="{{.}}"><i class="fa fa-twitter-square"></i></a>&nbsp;&nbsp;{{end}}

#{{ with .social }}
#  Contact me at:
#  Facebook: [{{ .GivenName }}](https://facebook.com/{{ .Social.facebook }})
#{{ end }}

#{{ if .Site.Params.social }}
#<div class="social-buttons">
#  {{ range .Site.Params.social }}
#    {{ if and (isset . "url") (isset . "icon") }}
#    <a href="{{ .url }}"><i class="fa lg fa-{{ .icon }}"></i></a>
#    {{ end }}
#  {{ end }}
#</div>
#{{ end }}
